### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by minanoun** [ssavvides/jope#1]
Hi,
thank you for this code,

I had this problem, could you help me please:

java.security.InvalidKeyException: Illegal key size
    at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
    at javax.crypto.Cipher.implInit(Cipher.java:805)
    at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
    at javax.crypto.Cipher.init(Cipher.java:1396)
    at javax.crypto.Cipher.init(Cipher.java:1327)
    at Pseuohomo.Coins.next(Coins.java:77)
    at Pseuohomo.Hgd.prngDraw(Hgd.java:60)
    at Pseuohomo.Hgd.hypergeometricHrua(Hgd.java:151)
    at Pseuohomo.Hgd.rhyper(Hgd.java:67)
    at Pseuohomo.OPE.sampleHGD(OPE.java:169)
    at Pseuohomo.OPE.encryptRecursive(OPE.java:60)
    at Pseuohomo.OPE.encrypt(OPE.java:35)
    at Pseuohomo.OPE.main(OPE.java:191)
Exception in thread "main" java.lang.NullPointerException
    at Pseuohomo.Coins.next(Coins.java:94)
    at Pseuohomo.Hgd.prngDraw(Hgd.java:60)
    at Pseuohomo.Hgd.hypergeometricHrua(Hgd.java:151)
    at Pseuohomo.Hgd.rhyper(Hgd.java:67)
    at Pseuohomo.OPE.sampleHGD(OPE.java:169)
    at Pseuohomo.OPE.encryptRecursive(OPE.java:60)
    at Pseuohomo.OPE.encrypt(OPE.java:35)
    at Pseuohomo.OPE.main(OPE.java:191)

**Comment by ssavvides** [comment]
You need unlimited strength Java Cryptography Extension

e.g. for Java 8: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html

**Comment by aviland** [comment]
the problem is in Coins.java
 ---------------------------
 this.k = new SecretKeySpec(digest, "AES");
-----------------------------------
this line above is to generate a 32 bytes key
so I replace it with a new method as shown below
----------------------------
  public static SecretKeySpec getSecretKey(final String password) throws NoSuchPaddingException, InvalidKeyException {
        //返回生成指定算法密钥生成器的 KeyGenerator 对象
        KeyGenerator kg = null;
        try {
            kg = KeyGenerator.getInstance(KEY_ALGORITHM);
            //AES 要求密钥长度为 128
            kg.init(128, new SecureRandom(password.getBytes()));
            //生成一个密钥
            //   cipher = `Cipher.getInstance(DEFAULT_CIPHER_ALGORITHM);`
            SecretKey secretKey = kg.generateKey();
            // cipher.init(Cipher.ENCRYPT_MODE, secretKey);// 初始化为加密模式的密码器
            return new SecretKeySpec(secretKey.getEncoded(), KEY_ALGORITHM);// 转换为AES专用密钥
        } catch (NoSuchAlgorithmException ex) {
//            Logger.getLogger(AESUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
---------------------------
the code above will generate 16 bytes key
and is under the limit size (32 bytes is a illegal size)
