### ISSUE TITLE
runtime exception!

### ISSUE THREAD

**Issue by aviland** [ssavvides/jope#2]
run:
java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at jope.Coins.next(Coins.java:72)
	at jope.Hgd.prngDraw(Hgd.java:61)
	at jope.Hgd.hypergeometricHrua(Hgd.java:156)
	at jope.Hgd.rhyper(Hgd.java:69)
	at jope.OPE.sampleHGD(OPE.java:162)
	at jope.OPE.encryptRecursive(OPE.java:57)
	at jope.OPE.encrypt(OPE.java:35)
	at jope.OPE.main(OPE.java:184)
Exception in thread "main" java.lang.NullPointerException
	at jope.Coins.next(Coins.java:89)
	at jope.Hgd.prngDraw(Hgd.java:61)
	at jope.Hgd.hypergeometricHrua(Hgd.java:156)
	at jope.Hgd.rhyper(Hgd.java:69)
	at jope.OPE.sampleHGD(OPE.java:162)
	at jope.OPE.encryptRecursive(OPE.java:57)
	at jope.OPE.encrypt(OPE.java:35)
	at jope.OPE.main(OPE.java:184)
C:\Users\haypo\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
构建失败 (总时间: 0 秒)

**Comment by ssavvides** [comment]
Please check out: https://github.com/ssavvides/jope/issues/1
